apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: penguin-libs-base

namespace: penguin-libs

resources:
  - ../../manifests/namespace.yaml
  - ../../manifests/buildValidator/deployment.yaml
  - ../../manifests/buildValidator/service.yaml
