apiVersion: v1
kind: Service
metadata:
  name: build-validator
  namespace: penguin-libs
  labels:
    app: build-validator
spec:
  type: ClusterIP
  selector:
    app: build-validator
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
