name: K8s Smoke Tests
on:
  push:
    branches: [main, 'v*']
  pull_request:
    branches: [main, 'v*']

jobs:
  alpha-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup microk8s
        uses: balchua/microk8s-actions@v0.3.2
        with:
          channel: '1.28/stable'
          addons: '["dns","storage","rbac","ingress"]'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Run alpha smoke tests
        run: make k8s-alpha-deploy

      - name: Cleanup
        if: always()
        run: make k8s-cleanup
